### ISSUE TITLE
Add traceid header

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/web-http-utils#5]
~See https://www.w3.org/TR/trace-context/#traceparent-header-field-values. We will use a uuid to generate the trace-id component. The parent-id component could be a constant that the application generates... or something else.~

Edit: Our needs are fairly simple, so we will just add a custom `traceid` header, whose value will be a UUID (with hyphens removed), generated by the client application.

**Comment by dmgaldi** [comment]
I'm planning to go with `traceid` for the simplified header name unless you have any objections

**Comment by dmfalke** [comment]
This sounds good to me, thanks!
